AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  calculator_api

  Sample SAM Template for calculator_api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  APIStageName:
    Default: api
    Description: StageName of API Gateway deployment
    Type: String
  Audience:
    Description: Auth0 Audience
    Type: String
  TokenIssuer:
    Description: Auth0 Token Issuer
    Type: String
  JWKSUri:
    Description: Auth0 JWKS uri
    Type: String
  DBHost:
    Description: Database Host
    Type: String
  DBUser:
    Description: Database User
    Type: String
  DBPassword:
    Description: Database Password
    Type: String
  DBSchema:
    Description: Database Schema
    Type: String
Resources:
  AppApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CalculatorAPI
      StageName: !Ref APIStageName
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          MyAuthAuthorizer:
            FunctionArn: !GetAtt AuthAuthorizer.Arn
            FunctionInvokeRole: !GetAtt AuthAuthorizerRole.Arn
            FunctionPayloadType: TOKEN
        InvokeRole: NONE
  OperationsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: operations/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_SCHEMA: !Ref DBSchema
      VpcConfig:
        SecurityGroupIds:
          - sg-0cae655977afe517b
        SubnetIds:
          - subnet-0bdd5ab4ac70cf08d
      Events:
        Operations:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref AppApi
            Auth:
              Authorizer: MyAuthAuthorizer
  AuthAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth-authorizer/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          AUDIENCE: !Ref Audience
          TOKEN_ISSUER: !Ref TokenIssuer
          JWKS_URI: !Ref JWKSUri
      Architectures:
        - arm64
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OperationsApi:
    Description: "API Gateway endpoint URL for Operations function"
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/${APIStageName}/operations/"
  OperationsFunction:
    Description: "Operations Lambda Function ARN"
    Value: !GetAtt OperationsFunction.Arn
  OperationsFunctionIamRole:
    Description: "Implicit IAM Role created for Operations function"
    Value: !GetAtt OperationsFunctionRole.Arn
