AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  calculator_api

  Sample SAM Template for calculator_api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        AUDIENCE: calculator-api
        TOKEN_ISSUER: https://dev-sgrkcg6vdqaqjg2a.us.auth0.com/
        JWKS_URI: https://dev-sgrkcg6vdqaqjg2a.us.auth0.com/.well-known/jwks.json
Parameters:
  APIStageName:
    Default: api
    Description: StageName of API Gateway deployment
    Type: String
Resources:
  AppApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CalculatorAPI
      StageName: !Ref APIStageName
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          MyAuthAuthorizer:
            FunctionArn: !GetAtt AuthAuthorizer.Arn
            FunctionInvokeRole: !GetAtt AuthAuthorizerRole.Arn
            FunctionPayloadType: TOKEN
        InvokeRole: NONE
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      VpcConfig:
        SecurityGroupIds:
          - sg-0cae655977afe517b
        SubnetIds:
          - subnet-0bdd5ab4ac70cf08d
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref AppApi
            Auth:
              Authorizer: MyAuthAuthorizer
  AuthAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth-authorizer/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Hello World function"
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/${APIStageName}/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
